// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  elevated_intro_section: dynamic(() => import("./ElevatedIntroSection")),
  footer_column: dynamic(() => import("./FooterColumn")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  navigation_item: dynamic(() => import("./NavigationItem")),
};
