// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  elevated_intro_section: dynamic(() => import("./ElevatedIntroSection")),
  text_block: dynamic(() => import("./TextBlock")),
  waterfall_section: dynamic(() => import("./WaterfallSection")),
};
