import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { ViewTransition } from 'react'
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransition>
      <html lang="es">
        <body className={`${montserrat.variable} antialiased`}>
          <main className="page-pancake relative">
            <Header />
            {children}
            <Footer />
          </main>
        </body>
      </html>
    </ViewTransition>
  );
}
