// Code generated by Slice Machine. DO NOT EDIT.

import HeroBanner from './HeroBanner';
import SectionGridCards from './SectionGridCards';
import SectionHeading from './SectionHeading';
import SectionScroll from './SectionScroll';

export {
	HeroBanner,
	SectionGridCards,
	SectionHeading,
	SectionScroll,
};

export const components = {
	hero_banner: HeroBanner,
	section_grid_cards: SectionGridCards,
	hero_section_split: SectionHeading,
	section_scroll: SectionScroll,
};
